version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./models/database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: flask
    ports:
      - "5432:5432"

volumes:
  db_data:
